services:
  - docker

env:
  - UNITY_VERSION=2019.2.9f1

before_script:
  - set -e

script:
  - docker build --build-arg UNITY_VERSION=$UNITY_VERSION -t stanov/unity:$UNITY_VERSION .
  - echo $DOCKER_HUB_PASSWORD | docker login --username stanov --password-stdin
  - docker push stanov/unity:$UNITY_VERSION
