services:
  - docker

env:
  - UNITY_VERSION=2019.2.9f1

before_script:
  - set -e
  - sed -i "s/UNITY_VERSION/${UNITY_VERSION}/g" Dockerfile

script:
  - docker build -t unity .
  - echo $DOCKER_HUB_PASSWORD | docker login --username $DOCKER_HUB_USERNAME --password-stdin
  - docker tag unity ${DOCKER_HUB_USERNAME}/unity:$UNITY_VERSION
  - docker push ${DOCKER_HUB_USERNAME}/unity:$UNITY_VERSION
